### ISSUE TITLE
voice command

### ISSUE THREAD

**Issue by imrohit007** [ggeop/Python-voice-assistant#68]
voice command is not working. I am using this in ubuntu. but it does not recoginize any voice. please help

**Comment by ggeop** [comment]
Hi imrohit007! By default the input mode is 'text' and not 'voice'. You can change the value in line 65 from 'text' to 'voice' in Python-voice-assistant/blob/master/src/jarvis/jarvis/settings.py.
If you change this value and continue not working check if your microphone is configured properly in your machine. Else attach the error in this thread in order to investigate it :-)
